export type IconType = | PlatformTypes | ActionTypes | NavigationTypes

export type PlatformTypes =
    | "Facebook"
    | "Linkedin"
    | "Twitter"
    | "Pinterest"
    | "Reddit"
    | "Tumblr"
    | "YouTube"
    | "TikTok"
    | "Google"
    | "Apple"
    | "Github"
    | "Instagram"

export type ActionTypes = 
    | "exit"
    | "delete"
    | "edit"
    | "share"
    | "light"
    | "dark"
    | "add"

export type NavigationTypes = 
    | "Home" 
    | "Dashboard"
    | "Biller"
    | "Settings" 
    | "Contacts"
    | "Workspaces"
    | "Notification"
    | "Invite"
    | "Apps"
    | "Search"
    | "Help"
    | "Profile"
    | "Schedule"
    | "Menu"
    | "Invoice Details"
    | "Merchant"
    | "Notes"
    | "Payment"